version: "3.9"
services:

  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql5
    command: mysqld 
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "33060:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret1
      - MYSQL_USER=demo
      - MYSQL_DATABASE=demo
      - MYSQL_PASSWORD=secret2

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq-host
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitdata:/var/lib/rabbitmq"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  datagenerator:
    build: ./data_generation/producer
    container_name: producer
    image: python-datagenerator
    depends_on:
      rabbitmq:
        condition:
          service_healthy
    links:
      - rabbitmq

  spring:
    build: ./service
    container_name: spring_service
    restart: unless-stopped
    image: blueberry-service
    depends_on:
      rabbitmq:
          condition: service_healthy
    ports:
      - 8080:8080
    links:
     - rabbitmq
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/demo
      - spring.datasource.username=demo
      - spring.datasource.password=secret2
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.jpa.hibernate.ddl-auto=update
      - SPRING_RABBITMQ_HOST=rabbitmq

  react:
    build: ./reactApp
    container_name: react
    ports:
      - 3001:3000
    stdin_open: true
    restart: unless-stopped
    image: blueberrypi-reactapp

volumes:
  mysql-data:
    driver: local